#!/bin/bash
sed -i 's/fizão/$\phi$/g' arquivo
sed -i 's/fizinho/$\varphi$/g' arquivo
sed -i 's/{implica}/$\rightarrow$/g' arquivo
sed -i 's/{metaida}/$\Longrightarrow$/g' arquivo
sed -i 's/{metaback}/$\Longleftarrow$/g' arquivo
sed -i 's/{volta}/$\leftarrow/g' arquivo
sed -i 's/{sse}/$\leftrightarrow$/g' arquivo
sed -i 's/{infere}/$\vdash$/g' arquivo
sed -i 's/{ndeduz}/$\nvdash$/g' arquivo
sed -i 's/{satisfaz}/$\vDash$/g' arquivo
sed -i 's/{nmodelo}/$\nvDash$/g' arquivo
sed -i 's/{conseq}/$\Vdash$/g' arquivo
sed -i 's/{nq}/$\nVdash$/g' arquivo
sed -i 's/{menorigual}/$\leq$/g' arquivo
sed -i 's/{maiorigual}/$\geq$/g' arquivo
sed -i 's/{pertence}/$\in$/g' arquivo
sed -i 's/{contido}/$\subseteq$/g' arquivo
sed -i 's/{vazio}/$\oslash$/g' arquivo
